# Arreglos bidimensionales

## Carga de librerías

Para trabajar con arreglos se utiliza una librería de Python, numpy, que contiene las funciones para todo el tratamiento numérico (de ahí el nombre *numeric python*)

In [1]:
import numpy as np

## Creando un arreglo bidimensional

In [46]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Averiguando la dimensión del arreglo ...

In [47]:
a.ndim

2

## ¿Cuántas filas y cuántas columnas?

In [48]:
print("Filas = ", len(a))
print("Columnas = ", len(a[0]))
print("shape = ", a.shape)

Filas =  3
Columnas =  2
shape =  (3, 2)


## Acceso a los elementos

In [49]:
a[0][0] = 29
a

array([[29.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [50]:
a[1,1] = 6
a

array([[29.,  0.],
       [ 0.,  6.],
       [ 0.,  0.]])

## Algunas funciones

In [51]:
# Relleno
a.fill(12)
a

array([[12., 12.],
       [12., 12.],
       [12., 12.]])

In [56]:
# Cambia la disposición de los elementos
a = a.reshape((2,3))
a

array([[12., 12., 12.],
       [12., 12., 12.]])

In [57]:
a.shape

(2, 3)

In [59]:
a[1,2] = 15
a

array([[12., 12., 12.],
       [12., 12., 15.]])

In [61]:
a = a + [1,2,3]
a

array([[13., 14., 15.],
       [13., 14., 18.]])

In [62]:
b = np.diag(np.array([1, 2, 3, 4]))
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Otra forma de crear un arreglo bidimensional

In [66]:
A = [[15,25,4], 
     [12,45,67], 
     [2,5,1], 
     [18,28,7]]
A

[[15, 25, 4], [12, 45, 67], [2, 5, 1], [18, 28, 7]]

In [67]:
B = np.array(A)
B

array([[15, 25,  4],
       [12, 45, 67],
       [ 2,  5,  1],
       [18, 28,  7]])

In [68]:
B.argmax()

5

In [69]:
B.argmax(1)

array([1, 2, 1, 1])

In [71]:
B.argmax(0)

array([3, 1, 1])

In [41]:
filas = B.shape[0]
columnas = B.shape[1]
C = np.zeros(B.shape)
for fila in range(filas):
  for columna in range(columnas):
    C[fila, columna] = B[fila, columna]*2
C

array([[ 30.,  50.,   8.],
       [ 24.,  90., 134.],
       [  4.,  10.,   2.],
       [ 36.,  50., 134.]])

## Otra opción para crear una matriz

In [42]:
D = np.matrix(A)
D

matrix([[15, 25,  4],
        [12, 45, 67],
        [ 2,  5,  1],
        [18, 25, 67]])

In [43]:
D.reshape((3,4))

matrix([[15, 25,  4, 12],
        [45, 67,  2,  5],
        [ 1, 18, 25, 67]])

In [45]:
D.shape

(4, 3)

## Acceso usando slices

In [74]:
D[:,2]

matrix([[ 4],
        [67],
        [ 1],
        [67]])

## Algunas funciones útiles

In [78]:
X = np.matrix(np.arange(12).reshape((3,4)))
X

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [80]:
print("Uso 1 ==> {0}".format(X.sum()))
print("Uso 2 ==> {0}".format(X.sum(axis=1)))
print("Uso 3 ==> {0}".format(X.sum(axis=0)))

Uso 1 ==> 66
Uso 2 ==> [[ 6]
 [22]
 [38]]
Uso 3 ==> [[12 15 18 21]]


In [81]:
print("Uso 1 ==> {0}".format(X.mean()))
print("Uso 2 ==> {0}".format(X.mean(axis=1)))
print("Uso 3 ==> {0}".format(X.mean(axis=0)))

Uso 1 ==> 5.5
Uso 2 ==> [[1.5]
 [5.5]
 [9.5]]
Uso 3 ==> [[4. 5. 6. 7.]]


# Funciones

## Lo básico

In [10]:
def esPar(x):
  return x % 2 == 0

In [11]:
# Llamada a la función
print(esPar(13))
print(esPar(4))

False
True


In [13]:
def f(x,y):
  suma = 0
  for i in range(x,y+1):
    suma = suma + i
  return suma

In [14]:
print(f(2,5))

14


In [16]:
def f(n=10):
  r = 0
  for i in range(2,n+1,2):
    r = r + i
  return r

In [18]:
print(f(7))
print(f())

12
30


## Retornando más de un valor

In [35]:
def g(x):
  if x.ndim == 2:
    return len(x), len(x[0])

In [36]:
# Probamos la función
t = np.ones((4,5))
ra, rb = g(t)
print(ra, rb)

4 5


In [ ]:
def h(x):
  for f in range(x.shape[0]):
    r = r + 

# Excepciones

In [5]:
x = float(input("Número :"))
print("Número ingresado = {0: .2f}".format(x))

Número :5.5687
Número ingresado =  5.57


**Obsevación**

---



Ejecute las sentencias anteriores ingresando una letra en lugar de un número, ¿qué sucede?

In [2]:
try:
  x = float(input("Número :"))
  print("Número ingresado = {0: .2f}".format(x))
except ValueError:
  print("Valor ingresado es incorrecto")

Número :agapito
Valor ingresado es incorrecto


In [9]:
import random
exito = False 
adivinar = random.randint(1, 100)
while True:
  try:
    numero = int(input("Ingrese número: "))
    if numero == adivinar:
      print("Felicitaciones")
      exito = True
      break
    else:
      if numero > adivinar:
        print("El número que debe adivinar es menor")
      else:
        print("El número que debe adivinar es mayor")
      sigue = input("Desea seguir intentando? ")
      if sigue.upper() == 'N':
          break
  except ValueError:
    print("Valor incorrecto")
if not exito:
  print("El número que debía adivinar era ", adivinar)

Ingrese número: 12
El número que debe adivinar es mayor
Desea seguir intentando? 15
Ingrese número: 34
El número que debe adivinar es menor
Desea seguir intentando? s
Ingrese número: 15
El número que debe adivinar es menor
Desea seguir intentando? s
Ingrese número: 7
El número que debe adivinar es mayor
Desea seguir intentando? s
Ingrese número: 8
El número que debe adivinar es mayor
Desea seguir intentando? s
Ingrese número: 12
El número que debe adivinar es mayor
Desea seguir intentando? s
Ingrese número: 14
El número que debe adivinar es menor
Desea seguir intentando? s
Ingrese número: 13
Felicitaciones


# DataFrame